node {
#    stage('SCM Checkout'){
#        git branch: 'master', url: 'https://github.com/rabbanigithub/jenkins.git'
#    }
    stage('Install NGINX on remote server'){
        def apt_update = 'sudo apt update'
        def apt_install = 'sudo apt install -y nginx'
        sshagent(['b3e9356b-6c02-4a33-9f13-b36c68367023']) {
            sh "ssh -o StrictHostKeyChecking=no vagrant@10.11.12.90 ${apt_update}"
            sh "ssh -o StrictHostKeyChecking=no vagrant@10.11.12.90 ${apt_install}"
        }
    }
    stage('Copy web code to NGINX document root'){
        def createTmpDir = 'mkdir /tmp/tmpWebFiles'
        def tmpFileDir = '/tmp/tmpWebFiles'
	def CfgFile  = './nginx-web/nginx.conf'
        def webFiles  = './nginx-web/html-web/*'
	def mvCfgFile = 'sudo mv /tmp/tmpWebFiles/nginx.conf /etc/nginx/'
	def mvWebFiles = 'sudo mv /tmp/tmpWebFiles/* /var/www/html/'
	def rmTmpDir = 'sudo rm -fr /tmp/tmpWebFiles'
        sshagent(['b3e9356b-6c02-4a33-9f13-b36c68367023']) {
            sh "ssh -o StrictHostKeyChecking=no vagrant@10.11.12.90 ${createTmpDir}"
	    sh "scp -o StrictHostKeyChecking=no ${CfgFile} vagrant@10.11.12.90:${tmpFileDir}"
            sh "scp -o StrictHostKeyChecking=no ${webFiles} vagrant@10.11.12.90:${tmpFileDir}"
	    sh "ssh -o StrictHostKeyChecking=no vagrant@10.11.12.90 ${mvCfgFile}"
            sh "ssh -o StrictHostKeyChecking=no vagrant@10.11.12.90 ${mvWebFiles}"
            sh "ssh -o StrictHostKeyChecking=no vagrant@10.11.12.90 ${rmTmpDir}"
        }
    }
    stage('Start and enable NGINX server'){
        def startNGINX = 'sudo systemctl start nginx'
        def enableNGINX = 'sudo systemctl enable nginx'
        sshagent(['b3e9356b-6c02-4a33-9f13-b36c68367023']) {
            sh "ssh -o StrictHostKeyChecking=no vagrant@10.11.12.90 ${startNGINX}"
            sh "ssh -o StrictHostKeyChecking=no vagrant@10.11.12.90 ${enableNGINX}"
        }
    }
    stage('Allow HTTP service on UFW'){
        def ufwAllowService = 'sudo ufw allow http'
        def ufwReload = 'sudo ufw reload'
        sshagent(['b3e9356b-6c02-4a33-9f13-b36c68367023']) {
            sh "ssh -o StrictHostKeyChecking=no vagrant@10.11.12.90 ${ufwAllowService}"
            sh "ssh -o StrictHostKeyChecking=no vagrant@10.11.12.90 ${ufwReload}"
        }
    }
    stage('Check web service status'){
        def checkUrl = 'curl -I http://10.11.12.90'
        sshagent(['b3e9356b-6c02-4a33-9f13-b36c68367023']) {
            sh "ssh -o StrictHostKeyChecking=no vagrant@10.11.12.90 ${checkUrl}"
        }
    }
}
